server:
  port: 8888

management:
  endpoints:
    web:
      base-path: "/admin"
      exposure:
        include: "*"
  endpoint:
    env:
      post:
        enabled: true
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    
eureka:
  password: password
  client:
    serviceUrl:
      defaultZone: http://user:${eureka.password}@${EUREKA.HOST}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mango-park/config-repo
          basedir: target/config
          default-label: main
  rabbitmq:
    host: ${RABBITMQ_HOST}  # RabbitMQ 호스트 주소
    port: 5672  # RabbitMQ 포트 번호
    username: guest  # RabbitMQ 사용자 이름
    password: guest  # RabbitMQ 비밀번호

---
spring:
  config:
    activate:
      on-profile: cloud
eureka:
  password: password
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
  client:
    serviceUrl:
      defaultZone: ${vcap.services.${PREFIX:}eureka.credentials.uri:http://user:${eureka.password:}@${PREFIX:}eureka.${application.domain:cfapps.io}}/eureka/

